name: lg_controller
description: A basic Liquid Galaxy controller application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  dartssh2: ^2.2.3
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/kml1.kml
    - assets/kml2.kml